name: koolaid
version: 1.0-SNAPSHOT
main: me.capyright.Main
api-version: 1.13
commands:
  gamemode:
    aliases: [gm, gmc, gms, gmsp]
  koolaid:
    aliases: [help, kl, kooltheaid]
  verify:
  weather:
  clear:
    aliases: [ci, clearinventory]